//
//  PlanetWorker.swift
//  SolutisSW2023
//
//  Created by Gabriel Roveri on 03/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Faz requisições de rede, recupera algo da base de dados do CoreData
final class PlanetWorker: ApiWorker {
  func getPlanetsOrError(completion: @escaping (Result<[PlanetModel], ServiceError>) -> Void) {
      request(configuration: PlanetNetworkConfiguration.fetchPlanets, response: DefaultResponse<[PlanetModel]>.self) { result in
          switch result {
          case .success(let success):
              completion(.success(success.results))
          case .failure(let failure):
              completion(.failure(failure))
          }
      }
  }
}
